# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4244705a0ae813b724d1a0ec1c51cba7ca8138842a0b229d56b793eddf5b28606e8e464fd300c0527a1b1b2c46afc564b34116d64d6c806f7120b30f331530e0

test:
  secret_key_base: e5cafea35420fdefbe3a4b3eb86fed767d2bbd169453ccff050b5421e1fd9f2a04892233b9a22063a93fedea49dbb301c46aa5a6f204ddb4a44e72650994ebf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
